version: "3.9"
services:
  blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000

  cosmos-db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    mem_limit: 3G
    cpu_count: 2
    tty: true
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - 8081:8081
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
    volumes:
      - cosmos-db-volume:/data/db

volumes:
  cosmos-db-volume:
