# This file contains all common components used by all Firma Con IO APIs
Signer:
  type: object
  properties:
    id:
      type: string
      format: uuid

Clause:
  type: object
  properties:
    name:
      type: string

DocumentMetadata:
  type: object
  properties:
    name:
      type: string

DocumentToBeUploaded:
  allOf:
    - $ref: "#/DocumentMetadata"
    - type: object
      properties:
        uploadUrl:
          type: string
          format: uri
        clauses:
          type: array
          items:
            $ref: "#/Clause"

Document:
  allOf:
    - $ref: "#/DocumentMetadata"
    - type: object
      properties:
        url:
          type: string
          format: uri
        clauses:
          type: array
          items:
            allOf:
              - $ref: "#/Clause"
              - type: object
                properties:
                  accepted:
                    type: boolean
                    default: false
                  updatedAt:
                    type: string
                    format: date-time

SignatureRequestMeta:
  type: object
  properties:
    id:
      type: string
      format: uuid
    signerId:
      type: string
      format: uuid
    serviceId:
      type: string
      format: uuid
    createdAt:
      type: string
      format: date-time
    updateAt:
      type: string
      format: date-time
    status:
      type: string

DraftSignatureRequest:
  allOf:
    - $ref: "#/SignatureRequestMeta"
    - type: object
      properties:
        status:
          type: string
          enum: ["draft"]
        documents:
          type: array
          items:
            oneOf:
              - $ref: "#/Document"
              - $ref: "#/DocumentToBeUploaded"

SignatureRequest:
  allOf:
    - $ref: "#/SignatureRequestMeta"
    - type: object
      properties:
        status:
          type: string
          enum: ["forwarded"]
        forwardedAt:
          type: string
          format: date-time
        documents:
          type: array
          items:
            $ref: "#/Document"

FullfilledSignatureRequest:
  allOf:
    - $ref: "#/SignatureRequestMeta"
    - type: object
      properties:
        status:
          type: string
          enum: ["fullfilled"]
        forwardedAt:
          type: string
          format: date-time
        signedAt:
          type: string
          format: date-time
        documents:
          type: array
          items:
            $ref: "#/Document"
