parameters:
  - name: nodeVersionSpec
    type: string
    default: "16.x"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersionSpec)
    displayName: "Install Node.js"
  - task: Npm@1
    inputs:
      command: ci
    displayName: "Install dependencies"
