steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "Install Node.js"
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: "$(Pipeline.Workspace)/.npm"
    displayName: Cache npm
  - task: Npm@1
    inputs:
      command: ci
    displayName: "Install dependencies"
