parameters:
  # whether code must be checked-out with persisted credentials
  - name: "persistCredentials"
    type: string
    default: false
  # the branch, tag or commit to checkout
  - name: "gitReference"
    type: string
    default: "none"

steps:
  - template: templates/node-job-setup/template.yaml@pagopaCommons
    parameters:
      persistCredentials: ${{ parameters.persistCredentials }}
  - script: yarn generate:issuer-api-models
    displayName: "Generate model definitons for Issuer API"
  - script: yarn generate:tokenizer-api-models
    displayName: "Generate model definitons for Tokenizer API"
