/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

export enum ActivationStatusEnum {
  "ACTIVE" = "ACTIVE",

  "INACTIVE" = "INACTIVE",

  "PENDING" = "PENDING",
}

export type ActivationStatus = t.TypeOf<typeof ActivationStatus>;
export const ActivationStatus = enumType<ActivationStatusEnum>(
  ActivationStatusEnum,
  "ActivationStatus"
);
