/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { FiscalCode } from "./FiscalCode";
import { ActivationStatus } from "./ActivationStatus";
import * as t from "io-ts";

// required attributes
const ActivationPayloadR = t.interface({
  fiscal_code: FiscalCode,

  status: ActivationStatus,
});

// optional attributes
const ActivationPayloadO = t.partial({});

export const ActivationPayload = t.exact(
  t.intersection([ActivationPayloadR, ActivationPayloadO], "ActivationPayload")
);

export type ActivationPayload = t.TypeOf<typeof ActivationPayload>;
