/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ServiceId } from "./ServiceId";
import { FiscalCode } from "./FiscalCode";
import { ActivationStatus } from "./ActivationStatus";
import * as t from "io-ts";
import { NonNegativeInteger } from "@pagopa/ts-commons/lib/numbers";

// required attributes
const ActivationR = t.interface({
  service_id: ServiceId,

  fiscal_code: FiscalCode,

  status: ActivationStatus,

  version: NonNegativeInteger,
});

// optional attributes
const ActivationO = t.partial({});

export const Activation = t.exact(
  t.intersection([ActivationR, ActivationO], "Activation")
);

export type Activation = t.TypeOf<typeof Activation>;
