/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ServiceScope } from "./ServiceScope";
import * as t from "io-ts";
import { NonEmptyString } from "@pagopa/ts-commons/lib/strings";

/**
 * A set of metadata properties related to this service.
 */

// required attributes
const CommonServiceMetadataR = t.interface({
  scope: ServiceScope,
});

// optional attributes
const CommonServiceMetadataO = t.partial({
  description: NonEmptyString,

  web_url: NonEmptyString,

  app_ios: NonEmptyString,

  app_android: NonEmptyString,

  tos_url: NonEmptyString,

  privacy_url: NonEmptyString,

  address: NonEmptyString,

  phone: NonEmptyString,

  email: NonEmptyString,

  pec: NonEmptyString,

  cta: NonEmptyString,

  token_name: NonEmptyString,

  support_url: NonEmptyString,
});

export const CommonServiceMetadata = t.exact(
  t.intersection(
    [CommonServiceMetadataR, CommonServiceMetadataO],
    "CommonServiceMetadata"
  )
);

export type CommonServiceMetadata = t.TypeOf<typeof CommonServiceMetadata>;
