/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ServiceName } from "./ServiceName";
import { DepartmentName } from "./DepartmentName";
import { OrganizationName } from "./OrganizationName";
import { OrganizationFiscalCode } from "./OrganizationFiscalCode";
import { CIDR } from "./CIDR";
import { withDefault } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

/**
 * Common properties for a ServicePayload
 */

// required attributes
const CommonServicePayloadR = t.interface({
  service_name: ServiceName,

  department_name: DepartmentName,

  organization_name: OrganizationName,

  organization_fiscal_code: OrganizationFiscalCode,

  authorized_cidrs: t.readonlyArray(CIDR, "array of CIDR"),
});

// optional attributes
const CommonServicePayloadO = t.partial({
  version: t.Integer,

  require_secure_channels: withDefault(t.boolean, false),
});

export const CommonServicePayload = t.exact(
  t.intersection(
    [CommonServicePayloadR, CommonServicePayloadO],
    "CommonServicePayload"
  )
);

export type CommonServicePayload = t.TypeOf<typeof CommonServicePayload>;
