/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { DocumentMetadata } from "./DocumentMetadata";
import * as t from "io-ts";

// required attributes
const CreateProductBodyR = t.interface({
  documents: t.readonlyArray(DocumentMetadata, "array of DocumentMetadata")
});

// optional attributes
const CreateProductBodyO = t.partial({});

export const CreateProductBody = t.exact(
  t.intersection([CreateProductBodyR, CreateProductBodyO], "CreateProductBody")
);

export type CreateProductBody = t.TypeOf<typeof CreateProductBody>;
