/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const CreatedMessageR = t.interface({});

// optional attributes
const CreatedMessageO = t.partial({
  id: t.string,
});

export const CreatedMessage = t.exact(
  t.intersection([CreatedMessageR, CreatedMessageO], "CreatedMessage")
);

export type CreatedMessage = t.TypeOf<typeof CreatedMessage>;
