/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { PatternString } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

/**
 * A date in the format YYYY-MM-DD.
 */

export type DateUTC = t.TypeOf<typeof DateUTC>;
export const DateUTC = PatternString("[0-9]{4}-[0-9]{2}-[0-9]{2}");
