/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

/**
 * Paylod with access token to retrieve a EU Covid Certificate
 */

// required attributes
const EUCovidCertR = t.interface({
  auth_code: t.string,
});

// optional attributes
const EUCovidCertO = t.partial({});

export const EUCovidCert = t.exact(
  t.intersection([EUCovidCertR, EUCovidCertO], "EUCovidCert")
);

export type EUCovidCert = t.TypeOf<typeof EUCovidCert>;
