/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { UTCISODateFromString } from "@pagopa/ts-commons/lib/dates";
import * as t from "io-ts";

export type ExpirationDateTime = t.TypeOf<typeof ExpirationDateTime>;
export const ExpirationDateTime = UTCISODateFromString;
