/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ExternalCreatedMessageWithContent } from "./ExternalCreatedMessageWithContent";
import { MessageResponseNotificationStatus } from "./MessageResponseNotificationStatus";
import { MessageStatusValue } from "./MessageStatusValue";
import { ReadStatus } from "./ReadStatus";
import { PaymentStatus } from "./PaymentStatus";
import * as t from "io-ts";

// required attributes
const ExternalMessageResponseWithContentR = t.interface({
  message: ExternalCreatedMessageWithContent,
});

// optional attributes
const ExternalMessageResponseWithContentO = t.partial({
  notification: MessageResponseNotificationStatus,

  status: MessageStatusValue,

  read_status: ReadStatus,

  payment_status: PaymentStatus,
});

export const ExternalMessageResponseWithContent = t.exact(
  t.intersection(
    [ExternalMessageResponseWithContentR, ExternalMessageResponseWithContentO],
    "ExternalMessageResponseWithContent"
  )
);

export type ExternalMessageResponseWithContent = t.TypeOf<
  typeof ExternalMessageResponseWithContent
>;
