/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { ServicePayload } from "./ServicePayload";
import { ServiceMetadata } from "./ServiceMetadata";

// required attributes
const ExtendedServicePayload2R = t.interface({});

// optional attributes
const ExtendedServicePayload2O = t.partial({
  service_metadata: ServiceMetadata,
});

export const ExtendedServicePayload2 = t.exact(
  t.intersection(
    [ExtendedServicePayload2R, ExtendedServicePayload2O],
    "ExtendedServicePayload2"
  )
);

export type ExtendedServicePayload2 = t.TypeOf<typeof ExtendedServicePayload2>;

export const ExtendedServicePayload = t.intersection(
  [ServicePayload, ExtendedServicePayload2],
  "ExtendedServicePayload"
);

export type ExtendedServicePayload = t.TypeOf<typeof ExtendedServicePayload>;
