/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { CreatedMessageWithContent } from "./CreatedMessageWithContent";
import { FeatureLevelType } from "./FeatureLevelType";

// required attributes
const ExternalCreatedMessageWithContent2R = t.interface({
  feature_level_type: FeatureLevelType,
});

// optional attributes
const ExternalCreatedMessageWithContent2O = t.partial({});

export const ExternalCreatedMessageWithContent2 = t.exact(
  t.intersection(
    [ExternalCreatedMessageWithContent2R, ExternalCreatedMessageWithContent2O],
    "ExternalCreatedMessageWithContent2"
  )
);

export type ExternalCreatedMessageWithContent2 = t.TypeOf<
  typeof ExternalCreatedMessageWithContent2
>;

export const ExternalCreatedMessageWithContent = t.intersection(
  [CreatedMessageWithContent, ExternalCreatedMessageWithContent2],
  "ExternalCreatedMessageWithContent"
);

export type ExternalCreatedMessageWithContent = t.TypeOf<
  typeof ExternalCreatedMessageWithContent
>;
