/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";
import { withDefault } from "@pagopa/ts-commons/lib/types";

export enum FeatureLevelTypeEnum {
  "STANDARD" = "STANDARD",

  "ADVANCED" = "ADVANCED",
}

export type FeatureLevelType = t.TypeOf<typeof FeatureLevelTypeBase>;
const FeatureLevelTypeBase = enumType<FeatureLevelTypeEnum>(
  FeatureLevelTypeEnum,
  "FeatureLevelType"
);

export const FeatureLevelType = withDefault(
  FeatureLevelTypeBase,
  "STANDARD" as FeatureLevelType
);
