/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { PatternString } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

/**
 * To avoid sharing the citizens fiscal codes, the API will
 * provide the hex encoding of the SHA256 hash of the upper case fiscal code.
 */

export type FiscalCodeHash = t.TypeOf<typeof FiscalCodeHash>;
export const FiscalCodeHash = PatternString("[0-9a-f]{64}");
