/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { FiscalCode } from "./FiscalCode";
import * as t from "io-ts";

// required attributes
const FiscalCodePayloadR = t.interface({
  fiscal_code: FiscalCode,
});

// optional attributes
const FiscalCodePayloadO = t.partial({});

export const FiscalCodePayload = t.exact(
  t.intersection([FiscalCodePayloadR, FiscalCodePayloadO], "FiscalCodePayload")
);

export type FiscalCodePayload = t.TypeOf<typeof FiscalCodePayload>;
