/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

/**
 * Describes the citizen's profile, mostly interesting for preferences
 * attributes.
 */

// required attributes
const LimitedProfileR = t.interface({
  sender_allowed: t.boolean,
});

// optional attributes
const LimitedProfileO = t.partial({
  preferred_languages: t.readonlyArray(t.string, "array of string"),
});

export const LimitedProfile = t.exact(
  t.intersection([LimitedProfileR, LimitedProfileO], "LimitedProfile")
);

export type LimitedProfile = t.TypeOf<typeof LimitedProfile>;
