/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { NonEmptyString } from "@pagopa/ts-commons/lib/strings";

// required attributes
const LogoR = t.interface({
  logo: NonEmptyString,
});

// optional attributes
const LogoO = t.partial({});

export const Logo = t.exact(t.intersection([LogoR, LogoO], "Logo"));

export type Logo = t.TypeOf<typeof Logo>;
