/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { CreatedMessageWithContent } from "./CreatedMessageWithContent";
import { MessageResponseNotificationStatus } from "./MessageResponseNotificationStatus";
import { MessageStatusValue } from "./MessageStatusValue";
import * as t from "io-ts";

// required attributes
const MessageResponseWithContentR = t.interface({
  message: CreatedMessageWithContent,
});

// optional attributes
const MessageResponseWithContentO = t.partial({
  notification: MessageResponseNotificationStatus,

  status: MessageStatusValue,
});

export const MessageResponseWithContent = t.exact(
  t.intersection(
    [MessageResponseWithContentR, MessageResponseWithContentO],
    "MessageResponseWithContent"
  )
);

export type MessageResponseWithContent = t.TypeOf<
  typeof MessageResponseWithContent
>;
