/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const MessageCreatedResponseR = t.interface({});

// optional attributes
const MessageCreatedResponseO = t.partial({
  id: t.string,
});

export const MessageCreatedResponse = t.exact(
  t.intersection(
    [MessageCreatedResponseR, MessageCreatedResponseO],
    "MessageCreatedResponse"
  )
);

export type MessageCreatedResponse = t.TypeOf<typeof MessageCreatedResponse>;
