/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { WithinRangeString } from "@pagopa/ts-commons/lib/strings";

// required attributes
const MessageContentBaseR = t.interface({
  subject: WithinRangeString(10, 121),

  markdown: WithinRangeString(80, 10001),
});

// optional attributes
const MessageContentBaseO = t.partial({});

export const MessageContentBase = t.exact(
  t.intersection(
    [MessageContentBaseR, MessageContentBaseO],
    "MessageContentBase"
  )
);

export type MessageContentBase = t.TypeOf<typeof MessageContentBase>;
