/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

export enum MessageStatusValueEnum {
  "ACCEPTED" = "ACCEPTED",

  "THROTTLED" = "THROTTLED",

  "FAILED" = "FAILED",

  "PROCESSED" = "PROCESSED",

  "REJECTED" = "REJECTED",
}

/**
 * The processing status of a message.
 * "ACCEPTED": the message has been accepted and will be processed for delivery;
 *   we'll try to store its content in the user's inbox and notify him on his preferred channels
 * "THROTTLED": a temporary failure caused a retry during the message processing;
 *   any notification associated with this message will be delayed for a maximum of 7 days
 * "FAILED": a permanent failure caused the process to exit with an error, no notification will be sent for this message
 * "PROCESSED": the message was succesfully processed and is now stored in the user's inbox;
 *   we'll try to send a notification for each of the selected channels
 * "REJECTED": either the recipient does not exist, or the sender has been blocked
 */

export type MessageStatusValue = t.TypeOf<typeof MessageStatusValue>;
export const MessageStatusValue = enumType<MessageStatusValueEnum>(
  MessageStatusValueEnum,
  "MessageStatusValue"
);
