/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { OrganizationFiscalCode } from "./OrganizationFiscalCode";
import * as t from "io-ts";

/**
 * Metadata needed to explicit payment's payee.
 */

// required attributes
const PayeeR = t.interface({
  fiscal_code: OrganizationFiscalCode,
});

// optional attributes
const PayeeO = t.partial({});

export const Payee = t.exact(t.intersection([PayeeR, PayeeO], "Payee"));

export type Payee = t.TypeOf<typeof Payee>;
