/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { PaymentDataBase } from "./PaymentDataBase";
import { Payee } from "./Payee";

// required attributes
const PaymentData2R = t.interface({});

// optional attributes
const PaymentData2O = t.partial({
  payee: Payee,
});

export const PaymentData2 = t.exact(
  t.intersection([PaymentData2R, PaymentData2O], "PaymentData2")
);

export type PaymentData2 = t.TypeOf<typeof PaymentData2>;

export const PaymentData = t.intersection(
  [PaymentDataBase, PaymentData2],
  "PaymentData"
);

export type PaymentData = t.TypeOf<typeof PaymentData>;
