/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

export enum PaymentStatusEnum {
  "PAID" = "PAID",

  "NOT_PAID" = "NOT_PAID",
}

/**
 * Payment status enumeration
 */

export type PaymentStatus = t.TypeOf<typeof PaymentStatus>;
export const PaymentStatus = enumType<PaymentStatusEnum>(
  PaymentStatusEnum,
  "PaymentStatus"
);
