/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { WithinRangeString } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

/**
 * The field *Numero ricetta elettronica* identifies the medical prescription at national level.
 */

export type PrescriptionNRE = t.TypeOf<typeof PrescriptionNRE>;
export const PrescriptionNRE = WithinRangeString(15, 16);
