/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { WithinRangeString } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

/**
 * The field *Identificativo Unico di Prescrizione* identifies the medical prescription at regional level.
 */

export type PrescriptionIUP = t.TypeOf<typeof PrescriptionIUP>;
export const PrescriptionIUP = WithinRangeString(1, 17);
