/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { PrescriptionNRE } from "./PrescriptionNRE";
import { PrescriptionIUP } from "./PrescriptionIUP";
import { PrescriberFiscalCode } from "./PrescriberFiscalCode";
import * as t from "io-ts";

/**
 * Metadata needed to process medical prescriptions.
 */

// required attributes
const PrescriptionDataR = t.interface({
  nre: PrescriptionNRE,
});

// optional attributes
const PrescriptionDataO = t.partial({
  iup: PrescriptionIUP,

  prescriber_fiscal_code: PrescriberFiscalCode,
});

export const PrescriptionData = t.exact(
  t.intersection([PrescriptionDataR, PrescriptionDataO], "PrescriptionData")
);

export type PrescriptionData = t.TypeOf<typeof PrescriptionData>;
