/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ProductId } from "./ProductId";
import { DocumentMetadata } from "./DocumentMetadata";
import * as t from "io-ts";

// required attributes
const ProductDetailViewR = t.interface({
  id: ProductId,

  documents: t.readonlyArray(DocumentMetadata, "array of DocumentMetadata"),
});

// optional attributes
const ProductDetailViewO = t.partial({});

export const ProductDetailView = t.exact(
  t.intersection([ProductDetailViewR, ProductDetailViewO], "ProductDetailView")
);

export type ProductDetailView = t.TypeOf<typeof ProductDetailView>;
