/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

export enum ReadStatusEnum {
  "UNAVAILABLE" = "UNAVAILABLE",

  "UNREAD" = "UNREAD",

  "READ" = "READ",
}

/**
 * Api definition of read status enumeration
 */

export type ReadStatus = t.TypeOf<typeof ReadStatus>;
export const ReadStatus = enumType<ReadStatusEnum>(
  ReadStatusEnum,
  "ReadStatus"
);
