/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ProductId } from "./ProductId";
import * as t from "io-ts";
import { FiscalCode as FiscalCodeT } from "@pagopa/ts-commons/lib/strings";

// required attributes
const RequestSignatureBodyR = t.interface({
  productId: ProductId,

  fiscalCode: FiscalCodeT,
});

// optional attributes
const RequestSignatureBodyO = t.partial({});

export const RequestSignatureBody = t.exact(
  t.intersection(
    [RequestSignatureBodyR, RequestSignatureBodyO],
    "RequestSignatureBody"
  )
);

export type RequestSignatureBody = t.TypeOf<typeof RequestSignatureBody>;
