/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { StandardServiceMetadata } from "./StandardServiceMetadata";
import { SpecialServiceMetadata } from "./SpecialServiceMetadata";
import { CommonServiceMetadata } from "./CommonServiceMetadata";

export const ServiceMetadata = t.union(
  [StandardServiceMetadata, SpecialServiceMetadata, CommonServiceMetadata],
  "ServiceMetadata"
);

export type ServiceMetadata = t.TypeOf<typeof ServiceMetadata>;
