/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ServiceId } from "./ServiceId";
import * as t from "io-ts";

// required attributes
const ServiceIdCollectionR = t.interface({
  items: t.readonlyArray(ServiceId, "array of ServiceId"),
});

// optional attributes
const ServiceIdCollectionO = t.partial({});

export const ServiceIdCollection = t.exact(
  t.intersection(
    [ServiceIdCollectionR, ServiceIdCollectionO],
    "ServiceIdCollection"
  )
);

export type ServiceIdCollection = t.TypeOf<typeof ServiceIdCollection>;
