/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { NonEmptyString } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

/**
 * The name of the service. Will be added to the content of sent messages.
 */

export type ServiceName = t.TypeOf<typeof ServiceName>;
export const ServiceName = NonEmptyString;
