/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

export enum ServiceScopeEnum {
  "NATIONAL" = "NATIONAL",

  "LOCAL" = "LOCAL",
}

export type ServiceScope = t.TypeOf<typeof ServiceScope>;
export const ServiceScope = enumType<ServiceScopeEnum>(
  ServiceScopeEnum,
  "ServiceScope"
);
