/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { CommonServiceMetadata } from "./CommonServiceMetadata";
import { NonEmptyString } from "@pagopa/ts-commons/lib/strings";

// required attributes
const SpecialServiceMetadata2R = t.interface({
  category: t.string,
});

// optional attributes
const SpecialServiceMetadata2O = t.partial({
  custom_special_flow: NonEmptyString,
});

export const SpecialServiceMetadata2 = t.exact(
  t.intersection(
    [SpecialServiceMetadata2R, SpecialServiceMetadata2O],
    "SpecialServiceMetadata2"
  )
);

export type SpecialServiceMetadata2 = t.TypeOf<typeof SpecialServiceMetadata2>;

export const SpecialServiceMetadata = t.intersection(
  [CommonServiceMetadata, SpecialServiceMetadata2],
  "SpecialServiceMetadata"
);

export type SpecialServiceMetadata = t.TypeOf<typeof SpecialServiceMetadata>;
