/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { CommonServiceMetadata } from "./CommonServiceMetadata";

// required attributes
const StandardServiceMetadata2R = t.interface({
  category: t.string,
});

// optional attributes
const StandardServiceMetadata2O = t.partial({});

export const StandardServiceMetadata2 = t.exact(
  t.intersection(
    [StandardServiceMetadata2R, StandardServiceMetadata2O],
    "StandardServiceMetadata2"
  )
);

export type StandardServiceMetadata2 = t.TypeOf<
  typeof StandardServiceMetadata2
>;

export const StandardServiceMetadata = t.intersection(
  [CommonServiceMetadata, StandardServiceMetadata2],
  "StandardServiceMetadata"
);

export type StandardServiceMetadata = t.TypeOf<typeof StandardServiceMetadata>;
