/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { SubscriptionKeyType } from "./SubscriptionKeyType";
import * as t from "io-ts";

// required attributes
const SubscriptionKeyTypePayloadR = t.interface({
  key_type: SubscriptionKeyType,
});

// optional attributes
const SubscriptionKeyTypePayloadO = t.partial({});

export const SubscriptionKeyTypePayload = t.exact(
  t.intersection(
    [SubscriptionKeyTypePayloadR, SubscriptionKeyTypePayloadO],
    "SubscriptionKeyTypePayload"
  )
);

export type SubscriptionKeyTypePayload = t.TypeOf<
  typeof SubscriptionKeyTypePayload
>;
