/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const SubscriptionKeysR = t.interface({
  primary_key: t.string,

  secondary_key: t.string,
});

// optional attributes
const SubscriptionKeysO = t.partial({});

export const SubscriptionKeys = t.exact(
  t.intersection([SubscriptionKeysR, SubscriptionKeysO], "SubscriptionKeys")
);

export type SubscriptionKeys = t.TypeOf<typeof SubscriptionKeys>;
