/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { DateUTC } from "./DateUTC";
import { SubscriptionsList } from "./SubscriptionsList";
import * as t from "io-ts";

// required attributes
const SubscriptionsFeedR = t.interface({
  dateUTC: DateUTC,

  subscriptions: SubscriptionsList,

  unsubscriptions: SubscriptionsList,
});

// optional attributes
const SubscriptionsFeedO = t.partial({});

export const SubscriptionsFeed = t.exact(
  t.intersection([SubscriptionsFeedR, SubscriptionsFeedO], "SubscriptionsFeed")
);

export type SubscriptionsFeed = t.TypeOf<typeof SubscriptionsFeed>;
