/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

export enum SubscriptionKeyTypeEnum {
  "PRIMARY_KEY" = "PRIMARY_KEY",

  "SECONDARY_KEY" = "SECONDARY_KEY",
}

export type SubscriptionKeyType = t.TypeOf<typeof SubscriptionKeyType>;
export const SubscriptionKeyType = enumType<SubscriptionKeyTypeEnum>(
  SubscriptionKeyTypeEnum,
  "SubscriptionKeyType"
);
