/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { FiscalCodeHash } from "./FiscalCodeHash";

export type SubscriptionsList = t.TypeOf<typeof SubscriptionsList>;
export const SubscriptionsList = t.readonlyArray(
  FiscalCodeHash,
  "array of FiscalCodeHash"
);
