/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { Timestamp } from "./Timestamp";
import { withDefault } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";
import { NonEmptyString } from "@pagopa/ts-commons/lib/strings";

/**
 * Payload containing all information needed to retrieve and visualize third party message details
 */

// required attributes
const ThirdPartyDataR = t.interface({
  id: NonEmptyString,
});

// optional attributes
const ThirdPartyDataO = t.partial({
  original_sender: NonEmptyString,

  original_receipt_date: Timestamp,

  has_attachments: withDefault(t.boolean, false),

  summary: NonEmptyString,
});

export const ThirdPartyData = t.exact(
  t.intersection([ThirdPartyDataR, ThirdPartyDataO], "ThirdPartyData")
);

export type ThirdPartyData = t.TypeOf<typeof ThirdPartyData>;
