/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const UploadTokenR = t.interface({
  documentId: t.string,

  token: t.string,
});

// optional attributes
const UploadTokenO = t.partial({});

export const UploadToken = t.exact(
  t.intersection([UploadTokenR, UploadTokenO], "UploadToken")
);

export type UploadToken = t.TypeOf<typeof UploadToken>;
