/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { CommonServicePayload } from "./CommonServicePayload";
import { CommonServiceMetadata } from "./CommonServiceMetadata";

/**
 * A payload used to create/update a service that appears in the service list.
 */

// required attributes
const VisibleServicePayload2R = t.interface({
  is_visible: t.literal(true),

  service_metadata: CommonServiceMetadata,
});

// optional attributes
const VisibleServicePayload2O = t.partial({});

export const VisibleServicePayload2 = t.exact(
  t.intersection(
    [VisibleServicePayload2R, VisibleServicePayload2O],
    "VisibleServicePayload2"
  )
);

export type VisibleServicePayload2 = t.TypeOf<typeof VisibleServicePayload2>;

export const VisibleServicePayload = t.intersection(
  [CommonServicePayload, VisibleServicePayload2],
  "VisibleServicePayload"
);

export type VisibleServicePayload = t.TypeOf<typeof VisibleServicePayload>;
