openapi: 3.0.3
info:
  title: IO Sign - User API
  version: 0.0.1
security:
  - FunctionsKey: []
paths:
  /signature-requests/{signatureRequestId}:
    get:
      operationId: getSignatureRequestById
      summary: Get a Signature Request By Id
      parameters:
        - in: path
          name: signatureRequestId
          schema:
            $ref: "#/components/schemas/SignatureRequestId"
          required: true
        - in: header
          name: FiscalCode
          schema:
            $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/schemas/FiscalCode"
          required: true
      responses:
        "200":
          description: The Signature Request detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignatureRequestDetailView"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        default:
          $ref: "#/components/responses/Unexpected"

  /qtsp/clauses:
    get:
      operationId: getQtspClauses
      summary: Get clauses list and MRC from QTSP
      responses:
        "200":
          description: The QTSP clauses list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QtspClauses"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        default:
          $ref: "#/components/responses/Unexpected"
  /signatures/{signatureId}:
    get:
      operationId: getSignatureById
      summary: Get a Signature By Id
      parameters:
        - in: path
          name: signatureId
          schema:
            $ref: "#/components/schemas/SignatureId"
          required: true
        - in: header
          name: FiscalCode
          schema:
            $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/schemas/FiscalCode"
          required: true
      responses:
        "200":
          description: The Signature Request detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignatureDetailView"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        default:
          $ref: "#/components/responses/Unexpected"

  /signatures:
    post:
      operationId: createSignature
      summary: Create a Signature from SignatureRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSignatureBody"
      parameters:
        - in: header
          name: FiscalCode
          schema:
            $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/schemas/FiscalCode"
          required: true
      responses:
        "201":
          description: Signature created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignatureDetailView"
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        default:
          $ref: "#/components/responses/Unexpected"

components:
  securitySchemes:
    FunctionsKey:
      type: apiKey
      name: X-Functions-Key
      in: header

  responses:
    NotFound:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/responses/NotFound"
    BadRequest:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/responses/BadRequest"
    Forbidden:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/responses/Forbidden"
    Unexpected:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/responses/Unexpected"
  schemas:
    SignatureRequestStatus:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/schemas/SignatureRequestStatus"
    ProductId:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/schemas/ProductId"
    Timestamp:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/schemas/Timestamp"
    QrCodeUrl:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/schemas/QrCodeUrl"
    Document:
      $ref: "https://raw.githubusercontent.com/pagopa/io-functions-sign/v1.0.0-RELEASE/openapi-issuer.yaml#/components/schemas/Document"

    SignatureRequestDetailView:
      type: object
      properties:
        id:
          type: string
          format: ulid
        status:
          $ref: "#/components/schemas/SignatureRequestStatus"
        productId:
          $ref: "#/components/schemas/ProductId"
        expiresAt:
          $ref: "#/components/schemas/Timestamp"
        qrCodeUrl:
          $ref: "#/components/schemas/QrCodeUrl"
        documents:
          type: array
          items:
            $ref: "#/components/schemas/Document"
      required:
        - id
        - productId
        - qrCodeUrl
        - documents
    SignatureRequestId:
      type: string
      format: ulid
      minLength: 1

    Email:
      type: string
      description: User's email.
      format: EmailString
      x-import: "@pagopa/ts-commons/lib/strings"
      example: me@example.com

    QtspClauses:
      type: object
      properties:
        clauses:
          type: array
          items:
            $ref: "#/components/schemas/QtspClause"
          minItems: 1
          uniqueItems: true
        mrcDocumentUrl:
          type: string
          format: uri
        privacyDocumentUrl:
          type: string
          format: uri
        tosDocumentUrl:
          type: string
          format: uri
      required:
        - text
        - mrcUrl

    QtspClause:
      type: object
      properties:
        text:
          type: string
      required:
        - text

    PublicKey:
      type: string
      format: base64url
      description: PEM public key encoded in base64

    SamlAssertion:
      type: string
      format: base64url
      description: SPID SAML assertion encoded in base64

    ClausesSignature:
      properties:
        type:
          type: string
          enum:
            - COORDS
            - UNIQUE_NAME
          description: base64 of coords object or fieldName string
        signatureFieldData:
          type: string
          description: uniqueName or base64(Coords) base64({x,y,w,h,page})
      description: accepted signature clause

    DocumentSignature:
      type: object
      properties:
        documentId:
          type: string
          format: ulid
        signature:
          type: string
          format: base64url
          description: Signature of document digest concatenated with document clauses
        clauses:
          type: array
          items:
            $ref: "#/components/schemas/ClausesSignature"
      required:
        - documentId
        - signature
        - clauses

    QtspClausesMetadata:
      type: object
      properties:
        acceptedClauses:
          type: array
          items:
            $ref: "#/components/schemas/QtspClause"
          minItems: 1
          uniqueItems: true
        mrcDocumentUrl:
          type: string
          format: uri
        signature:
          type: string
          format: base64url
          description: Signature of MRC digest concatenated with QTSP accepted clauses
      required:
        - acceptedClauses
        - mrcDocumentUrl
        - signature

    CreateSignatureBody:
      type: object
      properties:
        signatureRequestId:
          $ref: "#/components/schemas/SignatureRequestId"
        email:
          $ref: "#/components/schemas/Email"
        publicKey:
          $ref: "#/components/schemas/PublicKey"
        spidSamlAssertion:
          $ref: "#/components/schemas/SamlAssertion"
        documentSignatures:
          type: array
          items:
            $ref: "#/components/schemas/DocumentSignature"
          minItems: 1
          uniqueItems: true
        qtspClauses:
          $ref: "#/components/schemas/QtspClausesMetadata"
      required:
        - signatureRequestId
        - email
        - publicKey
        - spidSamlAssertion
        - documentSignatures
        - qtspClauses

    SignatureId:
      type: string
      format: ulid
      minLength: 1

    SignatureDetailView:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/SignatureId"
        signatureRequestId:
          $ref: "#/components/schemas/SignatureRequestId"
        email:
          $ref: "#/components/schemas/Email"
        publicKey:
          $ref: "#/components/schemas/PublicKey"
        spidSamlAssertion:
          $ref: "#/components/schemas/SamlAssertion"
        documentSignatures:
          type: array
          items:
            $ref: "#/components/schemas/DocumentSignature"
        qtspClauses:
          $ref: "#/components/schemas/QtspClausesMetadata"
        timestamp:
          $ref: "#/components/schemas/Timestamp"
      required:
        - id
        - signatureRequestId
        - email
        - publicKey
        - spidSamlAssertion
        - documentSignatures
        - qtspClauses
        - timestamp
